### ISSUE TITLE
When the parameter option.hoodie.path is not set, NullPointerException is triggered 

### ISSUE THREAD

**Issue by ThroughWeb** [AirToSupply/hudi-spark-plus#3]
=== Streaming Query ===
Identifier: [id = caa72aee-57cd-447b-a8de-fa98cb67f857, runId = 51d49a0a-a17b-4312-817e-3f60a4c592f2]
Current Committed Offsets: {MLSQLBinLogSource(ExecutorBinlogServer(172.16.2.120,43352),org.apache.spark.sql.SparkSession@321161a3,hdfs://2-120:9000/hudi/tmp/spark-cdc-hudi-sync-suite/sources/0,Some(10000000277700),Map(binglognameprefix -> mysql-bin, tablenamepattern -> tb_refund_payment_method_his, databasenamepattern -> db_issue_clear, binlogindex -> 1, username -> root, host -> 172.16.2.120, port -> 3306, binlogserverid -> 3f501dff-7396-439f-9014-11ad3641d1de, binlogfileoffset -> 277700, password -> 123456)): 10000000277949}
Current Available Offsets: {MLSQLBinLogSource(ExecutorBinlogServer(172.16.2.120,43352),org.apache.spark.sql.SparkSession@321161a3,hdfs://2-120:9000/hudi/tmp/spark-cdc-hudi-sync-suite/sources/0,Some(10000000277700),Map(binglognameprefix -> mysql-bin, tablenamepattern -> tb_refund_payment_method_his, databasenamepattern -> db_issue_clear, binlogindex -> 1, username -> root, host -> 172.16.2.120, port -> 3306, binlogserverid -> 3f501dff-7396-439f-9014-11ad3641d1de, binlogfileoffset -> 277700, password -> 123456)): 10000000279417}

Current State: ACTIVE
Thread State: RUNNABLE

Logical Plan:
MLSQLBinLogSource(ExecutorBinlogServer(172.16.2.120,43352),org.apache.spark.sql.SparkSession@321161a3,hdfs://2-120:9000/hudi/tmp/spark-cdc-hudi-sync-suite/sources/0,Some(10000000277700),Map(binglognameprefix -> mysql-bin, tablenamepattern -> tb_refund_payment_method_his, databasenamepattern -> db_issue_clear, binlogindex -> 1, username -> root, host -> 172.16.2.120, port -> 3306, binlogserverid -> 3f501dff-7396-439f-9014-11ad3641d1de, binlogfileoffset -> 277700, password -> 123456))
        at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:354)
        at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:244)
Caused by: java.lang.NullPointerException
        at org.apache.spark.sql.hudi.commands.BinlogSyncHoodieCommand$.$anonfun$sink$10(BinlogSyncHoodieCommand.scala:163)
        at scala.collection.MapLike.getOrElse(MapLike.scala:131)
        at scala.collection.MapLike.getOrElse$(MapLike.scala:129)
        at scala.collection.AbstractMap.getOrElse(Map.scala:63)
        at org.apache.spark.sql.hudi.commands.BinlogSyncHoodieCommand$.$anonfun$sink$1(BinlogSyncHoodieCommand.scala:161)
        at org.apache.spark.sql.hudi.commands.BinlogSyncHoodieCommand$.$anonfun$sink$1$adapted(BinlogSyncHoodieCommand.scala:125)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:181)
        at org.apache.spark.sql.hudi.commands.BinlogSyncHoodieCommand$.sink(BinlogSyncHoodieCommand.scala:125)
        at org.apache.spark.sql.hudi.commands.BinlogSyncHoodieCommand$.run(BinlogSyncHoodieCommand.scala:273)
        at org.apache.spark.sql.hudi.sources.BinlogHoodieSink.addBatch(BinlogHoodieSink.scala:19)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runBatch$16(MicroBatchExecution.scala:586)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runBatch$15(MicroBatchExecution.scala:584)
        at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:357)
        at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:355)
        at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:68)
20187 [launch-binlog-socket-server-in-spark-job] INFO  org.apache.spark.scheduler.DAGScheduler  - Job 0 failed: start at HoodieBinlogDeltaStreamer.scala:103, took 13.640881 s

**Comment by AirToSupply** [comment]
I've solved it!
